# Generated by Django 3.2.7 on 2022-04-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_one', '0002_auto_20220405_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_longitude', models.IntegerField()),
                ('user_latitude', models.IntegerField()),
                ('user_ip', models.GenericIPAddressField()),
                ('user_city', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_time', models.DateField()),
                ('weather_forecast', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.user_account')),
            ],
        ),
    ]
