# Generated by Django 3.2.7 on 2022-04-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo_info',
            name='requested_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='geo_info',
            name='user_latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geo_info',
            name='user_longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
