# Generated by Django 3.2.7 on 2022-04-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0002_auto_20220405_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo_info',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
